// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//flutter pub add firebase_core cloud_firestore firebase_auth firebase_ai

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3RmG_-7V-PGWpjmd5Ub9EfD2pSqoIq80',
    appId: '1:234274869677:web:a6a0491e62fd95ff975124',
    messagingSenderId: '234274869677',
    projectId: 'app-tarefas-vini',
    authDomain: 'app-tarefas-vini.firebaseapp.com',
    storageBucket: 'app-tarefas-vini.firebasestorage.app',
    measurementId: 'G-37XPVVBG3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQXSthKgY2cjQ9fVm4DXcoZ53oocPr3zA',
    appId: '1:234274869677:android:d18588da9e5eb529975124',
    messagingSenderId: '234274869677',
    projectId: 'app-tarefas-vini',
    storageBucket: 'app-tarefas-vini.firebasestorage.app',
  );
}
